#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias \
  vi="nvim" vim="nvim" \
  vidiff="nvim -d" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
  batt="cat /sys/class/power_supply/BAT?/capacity" \
  mkd="mkdir -pv" \
  mkdir="mkdir -pv" \
  ll="ls -l" \
  la="ls -lA" \
  ..="cd .." \
  df="df -h" \
  du="du -ch" \
  psxk="ps    --ppid 2 -p 2 --deselect" \
  psuk="ps u  --ppid 2 -p 2 --deselect" \
  psak="ps au --ppid 2 -p 2 --deselect"
  # cp="cp -v" \
  # mv="mv -v" \
  # rm="rm -v" \

# Colorize commands when possible (OSX)
ls -GFHh > /dev/null 2>&1 && alias \
  ls="ls -GFHh" \
  grep="grep --color=auto"

# Colorize commands when possible (Linux/BSD).
ls -hN --color=auto > /dev/null 2>&1 && alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi"

# trick to pass aliases with sudo/doas
# https://wiki.archlinux.org/index.php/Sudo#Passing_aliases
alias sudo='sudo '
alias doas='doas '


# https://github.com/chubin/wttr.in
alias weather='curl http://wttr.in'
alias weatherny='curl http://wttr.in/New_York'
alias weatherla='curl http://wttr.in/Los_Angeles'
alias weatherta='curl http://wttr.in/Tel_Aviv'

# custom programs
alias influx="influx -precision rfc3339"
alias dock="~/bin/dock-manager.sh dock"
alias undock="~/bin/dock-manager.sh undock"
alias dock-dual="~/bin/dock-manager.sh dock-dual"
alias lid-bind="echo 'PNP0C0D:00' | tee /sys/bus/acpi/drivers/button/bind"
alias lid-unbind="echo 'PNP0C0D:00' | tee /sys/bus/acpi/drivers/button/unbind"
alias alsamixer="alsamixer -c 1"
alias nextcloud="~/bin/Nextcloud"
# To install joplin:
# `mkdir ~/.joplin-bin/lib/node_modules`
# `NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin`
alias joplin="~/.joplin-bin/bin/joplin"
alias cryptomator="GDK_SCALE=2 /bin/cryptomator"
alias osync="/bin/osync.sh ~/.config/osync/dbx.conf"
alias proton-log="journalctl --user -u bridge -f"
alias open-ports="netstat -tulpn"
alias open-ports-pid="sudo netstat -tulpn"
alias fixmywifi="sudo modprobe -r brcmfmac && sudo modprobe brcmfmac"
alias source-kshrc="source ~/.kshrc"
alias source-zshrc="source ~/.config/zsh/.zshrc"
alias dracut-update="echo test | sudo dracut-hook install"
alias log-rotate="sudo logrotate -v /etc/logrotate.d/dns"
alias log-rotate-force="sudo logrotate -vf /etc/logrotate.d/dns"
alias unbound-adblock="sudo unbound-adhosts.sh"
alias svlog='f(){ tail $2 "/var/log/$1/current";  unset -f f; }; f'
#alias svlog='f(){ tail -f "/var/log/$@/current";  unset -f f; }; f'
alias temp-core="grep \"\" /sys/devices/platform/coretemp.?/hwmon/hwmon?/temp?_label; grep \"\" /sys/devices/platform/coretemp.?/hwmon/hwmon?/temp?_input | awk -F ':' 'BEGIN{print \"scale=2;\"}{print \$2\"/1000\"}' | bc"
alias temp-zone="grep \"\" /sys/class/thermal/thermal_zone?/temp; grep \"\" /sys/class/thermal/thermal_zone?/temp  | awk -F ':' 'BEGIN{print \"scale=2;\"}{print \$2\"/1000\"}' | bc"

if [ $EUID -ne 0 ]; then
  alias btrfs-snap="btrfs-snap-void"
else
  alias btrfs-snap="~bhagwan/bin/btrfs-snap-void"
fi

if command -v lsb_release > /dev/null 2>&1 && [ $(lsb_release -sc) = "void" ]; then
  alias unbound-log="svlog unbound -f"
  alias dnscrypt-log="svlog dnscrypt-proxy -f"
  alias xbps-cacherm-obsolete="xcleancache.sh pruneme 1"
  alias xbps-cacherm-uninstalled="xcleancache.sh notinstalled"
else
  alias unbound-log="journalctl -u unbound -f"
  alias dnscrypt-log="sudo tail -f /var/log/dnscrypt-proxy/query.log"
fi
