# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# do not add new line between prompts
# add_newline = false

[character]
# success_symbol  = "[>](bold green)"
# error_symbol = "[x](bold red)"
# success_symbol  = "[➜](green)"
success_symbol  = "[→](green)"
error_symbol = "[→](red)"
vicmd_symbol = "[V](bold blue)"

# indicator when sudo credentials are cached
[sudo]
disabled = false
symbol = " "
style = "bold blue"
format = "[$symbol]($style)"

[username]
show_always = false
format = "[$user]($style)"

[hostname]
format = "@[$hostname]($style) "

[directory]
truncation_length = 2
truncate_to_repo = true

# Workaround for gix (gitoxide) not being able to status $HOME
[git_status]
use_git_executable = true

[package]
# disabled = true
